pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                bat 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    bat "echo Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
                always {
                    script {
                        allure jsonReportDirectory: 'src/allure-results', results: [[path: 'src/allure-results']
                    }
                }
            }
        }
        stage('Deploy in Staging Environment'){
            steps{
                build job: 'deploy_to_staging_env'
            }
        }
    }
}